### ISSUE TITLE
Template 1C

### ISSUE THREAD

**Issue by inkostin** [nikimaxim/zbx-1c-server#1]
Value "???⠪??᪠? ?訡?? ? ????? 䠩??, ????? ????? ??? ??⪥ ⮬?." of type "string" is not suitable for value type "Numeric (unsigned)"

**Comment by nikimaxim** [comment]
In what item is happening?

Execute the command
powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\zbx_1c_server.ps1" lld db

**Comment by inkostin** [comment]
> 
> 
> In what item is happening?
> 
> Execute the command
> powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\zbx_1c_server.ps1" lld db

Work(Работает)

{"data":[{"{#CL.ID}":"ddf05646-2f70-4c6f-8979-582ca3cc0d60","{#CL.NAME}":"1C","{#CL.PORT}":1541,"{#CL.SERVER}":"1C","{#CLDB.ID}":"52cea105-13fb-439b-bcca-2cae703ba9a8","{#CLDB.DB}":"upp"},{"{#CL.ID}":"ddf05646-2f70-4c6f-8979-582ca3cc0d60","{#CL.NAME}":"1C","{#CL.PORT}":1541
.............

**Comment by inkostin** [comment]
UserParameter=1c.session[*],"C:\Program Files (x86)\1cv8\<working version>\bin\rac.exe" session --cluster="$1" --cluster-user=DOMAIN\USER --cluster-pwd=PASSWORD list --infobase="$2" | find /c "1CV8"

Правильно синтаксис?

**Comment by nikimaxim** [comment]
> Правильно синтаксис?
> UserParameter=1c.session[*],"C:\Program Files (x86)\1cv8<working version>\bin\rac.exe" session --cluster="$1" --cluster-user=DOMAIN\USER --cluster-pwd=PASSWORD list --infobase="$2" | find /c "1CV8

What version 1C x64?
Path to bin 1C?
Login password is on the cluster?

**Comment by inkostin** [comment]
> 
> 
> > Правильно синтаксис?
> > UserParameter=1c.session[*],"C:\Program Files (x86)\1cv8\bin\rac.exe" session --cluster="$1" --cluster-user=DOMAIN\USER --cluster-pwd=PASSWORD list --infobase="$2" | find /c "1CV8
> 
> What version 1C x64?
> Path to bin 1C?
> Login password is on the cluster?

1c - 8.3.14.1630
Windows Server 2019
C:\Program Files\1Cv8\

Start Service 1c - Domain\User
Cluster  - 1C, no user and password

**Comment by nikimaxim** [comment]
Add in zabbix agent UserParameter:

```
UserParameter=1c.discovery[*],powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\zbx_1c_server.ps1" $1 $2
UserParameter=1c.session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "1CV8"
UserParameter=1c.session-all[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list | find /c "1CV8"
UserParameter=1c.session-all-hibernate[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list | find /c ": yes"
UserParameter=1c.bgj[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "BackgroundJob"
UserParameter=1c.web-session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "WebClient"
UserParameter=1c.designer-session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "Designer"
UserParameter=1c.working-process[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" process --cluster="$1" list | find /c "process"
```

**Comment by inkostin** [comment]
UserParameter=1c.discovery[], - [*], ???

Value """C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe"" ?? ???? ????७??? ??? ???譥?
????????, ?ᯮ??塞?? ?ணࠬ??? ??? ?????? 䠩???." of type "string" is not suitable for value type "Numeric (unsigned)"

**Comment by nikimaxim** [comment]
> UserParameter=1c.discovery[], - [*], ??? 
corrected the code above

> C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe
do it:
https://github.com/nikimaxim/zbx-1c-server#add-service-ras-for-monitor-1c-server-cmd

**Comment by inkostin** [comment]
> 
> 
> > UserParameter=1c.discovery[], - [*], ???
> > corrected the code above
> 
> > C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe
> > do it:
> > https://github.com/nikimaxim/zbx-1c-server#add-service-ras-for-monitor-1c-server-cmd

I did not understand you.

**Comment by nikimaxim** [comment]
> > > UserParameter=1c.discovery[], - [*], ???
> > > corrected the code above
> > 
> > 
> > > C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe
> > > do it:
> > > https://github.com/nikimaxim/zbx-1c-server#add-service-ras-for-monitor-1c-server-cmd
> 
> I did not understand you.

Use this:
```
UserParameter=1c.discovery[*],powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\zbx_1c_server.ps1" $1 $2
UserParameter=1c.session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "1CV8"
UserParameter=1c.session-all[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list | find /c "1CV8"
UserParameter=1c.session-all-hibernate[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list | find /c ": yes"
UserParameter=1c.bgj[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "BackgroundJob"
UserParameter=1c.web-session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "WebClient"
UserParameter=1c.designer-session[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" session --cluster="$1" list --infobase="$2" | find /c "Designer"
UserParameter=1c.working-process[*],"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" process --cluster="$1" list | find /c "process"
```

**Comment by inkostin** [comment]
(((
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '??㬥?? "C:\Program Files\Zabbix Agent\zbx_1c_server.ps1" ??? ??ࠬ??? -File ?? ???????. ?????? ???? ? ???????饬? 䠩?? ? ???७??? ".ps1" ? ????⢥ ?

**Comment by nikimaxim** [comment]
> (((
> Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '??㬥?? "C:\Program Files\Zabbix Agent\zbx_1c_server.ps1" ??? ??ࠬ??? -File ?? ???????. ?????? ???? ? ???????饬? 䠩?? ? ???७??? ".ps1" ? ????⢥ ?

What will? PowerShell
`powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\zbx_1c_server.ps1" lld db`

**Comment by inkostin** [comment]
> powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\zbx_1c_server.ps1" lld db

PS C:\Users\inkostin> powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zbx_1c_server.ps1" lld db
{"data":[{"{#CL.ID}":"ddf05646-2f70-4c6f-8979-582ca3cc0d60","{#CL.NAME}":"1C","{#CL.PORT}":1541,"{#CL.SERVER}":"1C","{#CLDB.ID}":"52cea105-13fb-439b-bcca-2cae703ba9a8","{#CLDB.DB}":"upp"},{"{#CL.ID}":"ddf05646-2f70-4c6f-8979-582ca3cc0d60","{#CL.NAME}":"1C","{#CL.PORT}":15
.................

working...

**Comment by nikimaxim** [comment]
Zabbix Web > Monitoring > Latest Data > filter(Application: 1C server).
Send screenshot

**Comment by inkostin** [comment]
> 
> 
> Zabbix Web > Monitoring > Latest Data > filter(Application: 1C server).
> Send screenshot

https://radikal.ru][img]https://a.radikal.ru/a22/1910/45/f9af0be7c480.png

https://a.radikal.ru/a21/1910/69/1115ec57c80b.png

**Comment by nikimaxim** [comment]
Work?
`C:\Program Files\Zabbix Agent\\zabbix_agentd.exe -c C:\Program Files\Zabbix Agent\\zabbix_agentd.conf -t 1c.discovery["lld, db"]`

**Comment by inkostin** [comment]
> 
> 
> Work?
> `C:\Program Files\Zabbix Agent\\zabbix_agentd.exe -c C:\Program Files\Zabbix Agent\\zabbix_agentd.conf -t 1c.discovery["lld, db"]`

Work!

**Comment by nikimaxim** [comment]
Send screenshot discovery host. 
Problem in zabbix server.!

**Comment by nikimaxim** [comment]
Did you manage to find a problem?

**Comment by inkostin** [comment]
> 
> 
> Did you manage to find a problem?

No.

**Comment by inkostin** [comment]
> 
> 
> Did you manage to find a problem?

https://a.radikal.ru/a01/1910/b8/c17631005197.png

**Comment by nikimaxim** [comment]
On detection at you everything fulfills. 
Items added in Zabbix Web > Host > 1C > Items?
Name: 1C cluster DB discovery: *

**Comment by nikimaxim** [comment]
does it work?

**Comment by 3ebpaaa** [comment]
Привет! Не могу запустить в работу шаблон, пишет ошибку в Zabbix: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "Сервер r-1c-Test не является центральным для кластера 7dcfedac-924c-4942-b9e7-8c45330f9c8e.
0"
Вывод есть:
C:\Program Files\Zabbix Agent>.\zabbix_agentd.exe -c "C:\Program Files\Zabbix Agent\zabbix_agentd.d\user_agentd.conf" -t 1c.discovery[lld,cl]
1c.discovery[lld,cl]                          [t|{"data":[{"{#CL.ID}":"9699fe2b-1ab9-4f68-b348-aa2d0a645d8d","{#CL.NAME}":"local","{#CL.PORT}":1541,"{#CL.SERVER}":"r-1c-Test"}]}]

C:\Program Files\Zabbix Agent>.\zabbix_agentd.exe -c "C:\Program Files\Zabbix Agent\zabbix_agentd.d\user_agentd.conf" -t 1c.discovery[lld,db]
1c.discovery[lld,db]                          [t|{"data":[{"{#CL.ID}":"9699fe2b-1ab9-4f68-b348-aa2d0a645d8d","{#CL.NAME}":"local","{#CL.PORT}":1541,"{#CL.SERVER}":"r-1c-Test","{#CLDB.ID}":"596361ff-9ab7-424b-8196-cacd541f113e","{#CLDB.DB}":"r-1c-Test"}]}]
