### ISSUE TITLE
Нет данных

### ISSUE THREAD

**Issue by DishinIR** [nikimaxim/zbx-1c-server#2]
Базы обнаружил но не может получить сведения, где искать причину?

**Comment by nikimaxim** [comment]
Всё по пунктам сделали.? https://github.com/nikimaxim/zbx-1c-server/blob/master/README.md

**Comment by nikimaxim** [comment]
У вас получилось?

**Comment by DishinIR** [comment]
> У вас получилось?

нет

**Comment by DishinIR** [comment]
при выполнении скрипта powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\zbx_1c_server.ps1" lld db все бд отображаются
