### ISSUE TITLE
Нет данных

### ISSUE THREAD

**Issue by DishinIR** [nikimaxim/zbx-1c-server#3]
Базы обнаружил но не может получить сведения, где искать причину? При проверке в ручную скриптов все работает.

**Comment by DishinIR** [comment]
![image](https://user-images.githubusercontent.com/56062309/93980515-64b1af00-fd87-11ea-9186-6edce4a2e22d.png)

**Comment by nikimaxim** [comment]
Discovery rules: Что пишет в столбце Status(Сообщения об ошибках)
1c.discovery[lld,db]
1c.discovery[lld,cl]

Так же в items: 
Какие статусы(Сообщения об ошибках) у обнаруженных метриках?

**Comment by DishinIR** [comment]
> Discovery rules: Что пишет в столбце Status(Сообщения об ошибках)
> 1c.discovery[lld,db]
> 1c.discovery[lld,cl]
> 
> Так же в items:
> Какие статусы(Сообщения об ошибках) у обнаруженных метриках?

Состояние активировано.
![image](https://user-images.githubusercontent.com/56062309/94004267-1b705800-fda5-11ea-9c03-6c6a1eb32694.png)

**Comment by nikimaxim** [comment]
Так же в items:
Какие статусы(Сообщения об ошибках) у обнаруженных метриках?

**Comment by DishinIR** [comment]
> items
![image](https://user-images.githubusercontent.com/56062309/94010067-16fc6d00-fdae-11ea-977e-c96d80642ba1.png)

**Comment by DishinIR** [comment]
Во всех все активирована.

**Comment by nikimaxim** [comment]
Вы скинули элементы данных(Items) из шаблона. Посмотрите элементы данных(Items) у самого хоста. в каком они состояний и есть ли они вообще?

**Comment by slothfk** [comment]
Полагаю смотреть надо в сторону настройки ServerActive у агента zabbix ;)

**Comment by DishinIR** [comment]
> Вы скинули элементы данных(Items) из шаблона. Посмотрите элементы данных(Items) у самого хоста. в каком они состояний и есть ли они вообще?

имеется состояние активирована все базы отображаются

**Comment by nikimaxim** [comment]
Скиньте сюда конфиг zabbix_agentd.conf

**Comment by DishinIR** [comment]
[zabbix_agentd.zip](https://github.com/nikimaxim/zbx-1c-server/files/5268309/zabbix_agentd.zip)

**Comment by nikimaxim** [comment]
Как выше и сказали(@slothfk ) у тебя ServerActive=127.0.0.1, а надо ServerActive=10.1.1.1(zabbix server ip)
И Hostname=Windows host должен соответствовать имени хоста в zabbix server

**Comment by DishinIR** [comment]
> Как выше и сказали(@slothfk ) у тебя ServerActive=127.0.0.1, а надо ServerActive=10.1.1.1(zabbix server ip)
> И Hostname=Windows host должен соответствовать имени хоста в zabbix server

имя хоста с доменом указывать?

**Comment by nikimaxim** [comment]
> > Как выше и сказали(@slothfk ) у тебя ServerActive=127.0.0.1, а надо ServerActive=10.1.1.1(zabbix server ip)
> > И Hostname=Windows host должен соответствовать имени хоста в zabbix server
> 
> имя хоста с доменом указывать?

Как у вас в админки сервера заббик указанно(Имя хоста где 1с крутится) так и в конфиги(zabbix_agentd.conf) должно быть.

**Comment by DishinIR** [comment]
> > > Как выше и сказали(@slothfk ) у тебя ServerActive=127.0.0.1, а надо ServerActive=10.1.1.1(zabbix server ip)
> > > И Hostname=Windows host должен соответствовать имени хоста в zabbix server
> > 
> > 
> > имя хоста с доменом указывать?
> 
> Как у вас в админки сервера заббик указанно(Имя хоста где 1с крутится) так и в конфиги(zabbix_agentd.conf) должно быть.

не помогло

**Comment by slothfk** [comment]
> не помогло

Попробуйте у какого-нибудь элемента данных (в шаблоне) сменить тип с **Zabbix агент (активный)** на просто **Zabbix агент** и посмотреть будут ли собираться данные по этому элементу (полагаю, что будут).

**Comment by DishinIR** [comment]
> > не помогло
> 
> Попробуйте у какого-нибудь элемента данных (в шаблоне) сменить тип с **Zabbix агент (активный)** на просто **Zabbix агент** и посмотреть будут ли собираться данные по этому элементу (полагаю, что будут).

После этого вышло не поддерживается и с ошибкой 
Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "???⥬? ?? 㤠???? ???? 㪠????? ????."

**Comment by nikimaxim** [comment]
> 
> После этого вышло не поддерживается и с ошибкой
> Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "???⥬? ?? 㤠???? ???? 㪠????? ????."

Add service RAS for monitor 1C Server: (CMD!)
sc create "1C:Enterprise RAS" binpath= "C:\Program Files (86)\1cv8\working version\bin\ras.exe cluster --service" obj= ".\USR1CV8" password= "" displayname= "1C:Enterprise RAS" start= auto

Эта служба настроина/работает?

**Comment by DishinIR** [comment]
> > После этого вышло не поддерживается и с ошибкой
> > Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "???⥬? ?? 㤠???? ???? 㪠????? ????."
> 
> Add service RAS for monitor 1C Server: (CMD!)
> sc create "1C:Enterprise RAS" binpath= "C:\Program Files (86)\1cv8\working version\bin\ras.exe cluster --service" obj= ".\USR1CV8" password= "" displayname= "1C:Enterprise RAS" start= auto
> 
> Эта служба настроина/работает?

да конечно, с указанием портов.
C:\Program Files (x86)\1cv8\8.3.17.1386\bin\ras.exe cluster --service --port=1641 localhost:1540

**Comment by slothfk** [comment]
> да конечно, с указанием портов.
> C:\Program Files (x86)\1cv8\8.3.17.1386\bin\ras.exe cluster --service --port=1641 localhost:1540

Если служба запущена так, как здесь написано, то она на нестандартном порту, который надо указать при вызове rac.exe, записанном в **UserParameter**

**Comment by DishinIR** [comment]
> > да конечно, с указанием портов.
> > C:\Program Files (x86)\1cv8\8.3.17.1386\bin\ras.exe cluster --service --port=1641 localhost:1540
> 
> Если служба запущена так, как здесь написано, то она на нестандартном порту, который надо указать при вызове rac.exe, записанном в **UserParameter**

UserParameter=1c.bgj[*],"C:\Program Files\1cv8\8.3.17.1386\bin\rac.exe" session --port=1641 --cluster="$1" list --infobase="$2" | find /c "BackgroundJob"
таким образом?

**Comment by slothfk** [comment]
> таким образом?

Коллега, Вы в документацию вообще не любите заглядывать? 
rac help запустите!

К примеру так
> UserParameter=1c.bgj[*],"C:\Program Files\1cv8\8.3.17.1386\bin\rac.exe" session localhost:1641 --cluster="$1" list --infobase="$2" | find /c "BackgroundJob"

**Comment by DishinIR** [comment]
Всем огромное спасибо, все работает:)

**Comment by DishinIR** [comment]
> > таким образом?
> 
> Коллега, Вы в документацию вообще не любите заглядывать?
> rac help запустите!
> 
> К примеру так
> 
> > UserParameter=1c.bgj[*],"C:\Program Files\1cv8\8.3.17.1386\bin\rac.exe" session localhost:1641 --cluster="$1" list --infobase="$2" | find /c "BackgroundJob"
